# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('game_id', models.CharField(max_length=32)),
                ('timestamp', models.CharField(max_length=32)),
                ('submission_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=32)),
                ('report', models.CharField(max_length=5000)),
            ],
        ),
    ]
