# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(default='?', max_length=32),
        ),
    ]
