# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiweb', '0003_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='rank',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='bot',
            name='selection_weight',
            field=models.DecimalField(decimal_places=12, default=1, max_digits=24),
        ),
    ]
