# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiweb', '0006_result_gamename'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='bot_errors',
            field=models.ManyToManyField(to='aiweb.BotError'),
        ),
    ]
