# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiweb', '0008_auto_20160213_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
