# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiweb', '0009_submission_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
    ]
